"""Add unique constraint to developers table

Revision ID: 1fa8bb9b5bfe
Revises: 49d56cc6183f
Create Date: 2025-11-21 22:06:16.951704

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fa8bb9b5bfe"
down_revision: Union[str, None] = "49d56cc6183f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_workspace_developer", "developers", ["workspace_id", "username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_workspace_developer", "developers", type_="unique")
    # ### end Alembic commands ###
