"""Add conversation hierarchy and semantic metadata fields

Revision ID: 22bc7db34fe9
Revises: 4b979fd13d96
Create Date: 2025-11-18 18:16:15.797288

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22bc7db34fe9"
down_revision: Union[str, None] = "4b979fd13d96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("parent_conversation_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "conversations",
        sa.Column(
            "conversation_type",
            sa.Enum(
                "main",
                "agent",
                "mcp",
                "skill",
                "command",
                "other",
                name="conversationtype",
                native_enum=False,
            ),
            server_default="main",
            nullable=False,
        ),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "context_semantics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "agent_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_conversations_conversation_type"),
        "conversations",
        ["conversation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_parent_conversation_id"),
        "conversations",
        ["parent_conversation_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "conversations",
        "conversations",
        ["parent_conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_index(
        op.f("ix_conversations_parent_conversation_id"), table_name="conversations"
    )
    op.drop_index(
        op.f("ix_conversations_conversation_type"), table_name="conversations"
    )
    op.drop_column("conversations", "agent_metadata")
    op.drop_column("conversations", "context_semantics")
    op.drop_column("conversations", "conversation_type")
    op.drop_column("conversations", "parent_conversation_id")
    # ### end Alembic commands ###
