"""Add children_count column to conversations

Revision ID: 49d56cc6183f
Revises: 005
Create Date: 2025-11-20 22:54:12.676963

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49d56cc6183f"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("children_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###

    # Backfill children_count for existing conversations
    op.execute(
        """
        UPDATE conversations c
        SET children_count = (
            SELECT COUNT(*)
            FROM conversations
            WHERE parent_conversation_id = c.id
        )
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "children_count")
    # ### end Alembic commands ###
