"""Add directory_path to Project model

Revision ID: 4b979fd13d96
Revises: df336668f2bd
Create Date: 2025-11-18 15:48:27.207218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b979fd13d96"
down_revision: Union[str, None] = "df336668f2bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("directory_path", sa.Text(), nullable=False))
    op.create_index(
        op.f("ix_projects_directory_path"), "projects", ["directory_path"], unique=False
    )
    op.create_unique_constraint(
        "uq_workspace_directory", "projects", ["workspace_id", "directory_path"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_workspace_directory", "projects", type_="unique")
    op.drop_index(op.f("ix_projects_directory_path"), table_name="projects")
    op.drop_column("projects", "directory_path")
    # ### end Alembic commands ###
