"""add_conversation_insights_table

Revision ID: 4c258c30a4b8
Revises: b2a1c0e4f204
Create Date: 2025-11-26 22:07:22.961535

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c258c30a4b8"
down_revision: Union[str, None] = "b2a1c0e4f204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "workflow_patterns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "productivity_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("collaboration_quality", sa.Integer(), nullable=False),
        sa.Column(
            "key_moments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "learning_opportunities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("agent_effectiveness", sa.Integer(), nullable=False),
        sa.Column("scope_clarity", sa.Integer(), nullable=False),
        sa.Column(
            "technical_debt_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("testing_behavior", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "quantitative_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("canonical_version", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "version", name="uq_conversation_insights_version"
        ),
    )
    op.create_index(
        op.f("ix_conversation_insights_conversation_id"),
        "conversation_insights",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_insights_expires_at"),
        "conversation_insights",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_insights_generated_at"),
        "conversation_insights",
        ["generated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_insights_generated_at"),
        table_name="conversation_insights",
    )
    op.drop_index(
        op.f("ix_conversation_insights_expires_at"), table_name="conversation_insights"
    )
    op.drop_index(
        op.f("ix_conversation_insights_conversation_id"),
        table_name="conversation_insights",
    )
    op.drop_table("conversation_insights")
    # ### end Alembic commands ###
