"""add collector multi-tenancy schema

Revision ID: c7103d6e90ac
Revises: 1cd100f1bde7
Create Date: 2025-11-16 14:27:44.393122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7103d6e90ac"
down_revision: Union[str, None] = "1cd100f1bde7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_is_active"), "organizations", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspaces_is_active"), "workspaces", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_workspaces_name"), "workspaces", ["name"], unique=False)
    op.create_index(
        op.f("ix_workspaces_organization_id"),
        "workspaces",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "collector_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("collector_type", sa.String(length=50), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=False),
        sa.Column("api_key_prefix", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("total_uploads", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_conversations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("last_upload_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collector_configs_api_key_hash"),
        "collector_configs",
        ["api_key_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_collector_configs_is_active"),
        "collector_configs",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collector_configs_last_heartbeat"),
        "collector_configs",
        ["last_heartbeat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collector_configs_workspace_id"),
        "collector_configs",
        ["workspace_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("conversation_tags_conversation_id_tag_type_tag_value_key"),
        "conversation_tags",
        type_="unique",
    )
    op.drop_index(op.f("idx_tags_conversation"), table_name="conversation_tags")
    op.drop_index(op.f("idx_tags_type"), table_name="conversation_tags")
    op.drop_index(op.f("idx_tags_value"), table_name="conversation_tags")
    op.add_column("conversations", sa.Column("workspace_id", sa.UUID(), nullable=False))
    op.add_column("conversations", sa.Column("collector_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("idx_conversations_agent"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_agent_time"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_developer"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_developer_time"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_project"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_project_time"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_status"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_status_time"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_success"), table_name="conversations")
    op.drop_index(
        op.f("idx_conversations_success_nonnull"),
        table_name="conversations",
        postgresql_where="(success IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_conversations_tags"),
        table_name="conversations",
        postgresql_using="gin",
    )
    op.drop_index(op.f("idx_conversations_time"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_updated_at"), table_name="conversations")
    op.create_index(
        op.f("ix_conversations_collector_id"),
        "conversations",
        ["collector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_success"), "conversations", ["success"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_updated_at"),
        "conversations",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_workspace_id"),
        "conversations",
        ["workspace_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "conversations",
        "collector_configs",
        ["collector_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "conversations",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("developers", sa.Column("workspace_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_developers_workspace_id"), "developers", ["workspace_id"], unique=False
    )
    op.create_foreign_key(
        None, "developers", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("epochs_conversation_id_sequence_key"), "epochs", type_="unique"
    )
    op.drop_index(op.f("idx_epochs_conversation"), table_name="epochs")
    op.drop_index(op.f("idx_epochs_intent"), table_name="epochs")
    op.drop_index(op.f("idx_epochs_sentiment"), table_name="epochs")
    op.drop_index(op.f("idx_epochs_time"), table_name="epochs")
    op.drop_index(op.f("idx_files_conversation"), table_name="files_touched")
    op.drop_index(op.f("idx_files_epoch"), table_name="files_touched")
    op.drop_index(op.f("idx_files_path"), table_name="files_touched")
    op.add_column("ingestion_jobs", sa.Column("collector_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("idx_ingestion_jobs_conversation"), table_name="ingestion_jobs")
    op.drop_index(
        op.f("idx_ingestion_jobs_failed"),
        table_name="ingestion_jobs",
        postgresql_where="((status)::text = 'failed'::text)",
    )
    op.drop_index(op.f("idx_ingestion_jobs_source_config"), table_name="ingestion_jobs")
    op.drop_index(op.f("idx_ingestion_jobs_source_time"), table_name="ingestion_jobs")
    op.drop_index(op.f("idx_ingestion_jobs_source_type"), table_name="ingestion_jobs")
    op.drop_index(op.f("idx_ingestion_jobs_started_at"), table_name="ingestion_jobs")
    op.drop_index(op.f("idx_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("idx_ingestion_jobs_status_time"), table_name="ingestion_jobs")
    op.create_index(
        op.f("ix_ingestion_jobs_collector_id"),
        "ingestion_jobs",
        ["collector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_source_type"),
        "ingestion_jobs",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_started_at"),
        "ingestion_jobs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False
    )
    op.create_foreign_key(
        None,
        "ingestion_jobs",
        "collector_configs",
        ["collector_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("idx_messages_content_fts"), table_name="messages", postgresql_using="gin"
    )
    op.drop_index(op.f("idx_messages_conversation"), table_name="messages")
    op.drop_index(op.f("idx_messages_conversation_role"), table_name="messages")
    op.drop_index(
        op.f("idx_messages_entities"), table_name="messages", postgresql_using="gin"
    )
    op.drop_index(op.f("idx_messages_epoch"), table_name="messages")
    op.drop_index(op.f("idx_messages_timestamp"), table_name="messages")
    op.drop_constraint(
        op.f("messages_epoch_id_sequence_key"), "messages", type_="unique"
    )
    op.add_column("projects", sa.Column("workspace_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False
    )
    op.create_foreign_key(
        None, "projects", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "raw_logs",
        "last_processed_offset",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Byte offset in file where we last stopped parsing",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "raw_logs",
        "last_processed_line",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Line number for debugging/human readability",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "raw_logs",
        "file_size_bytes",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="File size at last parse (detect truncation)",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "raw_logs",
        "partial_hash",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Hash of content up to last_processed_offset",
        existing_nullable=True,
    )
    op.alter_column(
        "raw_logs",
        "last_message_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of last processed message (validation)",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_raw_logs_agent_type"), table_name="raw_logs")
    op.drop_index(op.f("idx_raw_logs_conversation"), table_name="raw_logs")
    op.drop_index(op.f("idx_raw_logs_file_hash"), table_name="raw_logs")
    op.drop_index(op.f("idx_raw_logs_file_path"), table_name="raw_logs")
    op.drop_constraint(op.f("raw_logs_file_hash_key"), "raw_logs", type_="unique")
    op.create_index(
        op.f("ix_raw_logs_agent_type"), "raw_logs", ["agent_type"], unique=False
    )
    op.create_index(
        op.f("ix_raw_logs_file_hash"), "raw_logs", ["file_hash"], unique=True
    )
    op.create_index(
        op.f("ix_raw_logs_file_path"), "raw_logs", ["file_path"], unique=False
    )
    op.add_column(
        "watch_configurations", sa.Column("workspace_id", sa.UUID(), nullable=False)
    )
    op.drop_index(
        op.f("idx_watch_configs_directory"), table_name="watch_configurations"
    )
    op.drop_index(
        op.f("idx_watch_configs_is_active"), table_name="watch_configurations"
    )
    op.drop_index(op.f("idx_watch_configs_project"), table_name="watch_configurations")
    op.create_index(
        op.f("ix_watch_configurations_directory"),
        "watch_configurations",
        ["directory"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_configurations_is_active"),
        "watch_configurations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_configurations_workspace_id"),
        "watch_configurations",
        ["workspace_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "watch_configurations",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "watch_configurations", type_="foreignkey")
    op.drop_index(
        op.f("ix_watch_configurations_workspace_id"), table_name="watch_configurations"
    )
    op.drop_index(
        op.f("ix_watch_configurations_is_active"), table_name="watch_configurations"
    )
    op.drop_index(
        op.f("ix_watch_configurations_directory"), table_name="watch_configurations"
    )
    op.create_index(
        op.f("idx_watch_configs_project"),
        "watch_configurations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_watch_configs_is_active"),
        "watch_configurations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("idx_watch_configs_directory"),
        "watch_configurations",
        ["directory"],
        unique=False,
    )
    op.drop_column("watch_configurations", "workspace_id")
    op.drop_index(op.f("ix_raw_logs_file_path"), table_name="raw_logs")
    op.drop_index(op.f("ix_raw_logs_file_hash"), table_name="raw_logs")
    op.drop_index(op.f("ix_raw_logs_agent_type"), table_name="raw_logs")
    op.create_unique_constraint(
        op.f("raw_logs_file_hash_key"),
        "raw_logs",
        ["file_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_raw_logs_file_path"), "raw_logs", ["file_path"], unique=False
    )
    op.create_index(
        op.f("idx_raw_logs_file_hash"), "raw_logs", ["file_hash"], unique=True
    )
    op.create_index(
        op.f("idx_raw_logs_conversation"), "raw_logs", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("idx_raw_logs_agent_type"), "raw_logs", ["agent_type"], unique=False
    )
    op.alter_column(
        "raw_logs",
        "last_message_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of last processed message (validation)",
        existing_nullable=True,
    )
    op.alter_column(
        "raw_logs",
        "partial_hash",
        existing_type=sa.VARCHAR(length=64),
        comment="Hash of content up to last_processed_offset",
        existing_nullable=True,
    )
    op.alter_column(
        "raw_logs",
        "file_size_bytes",
        existing_type=sa.INTEGER(),
        comment="File size at last parse (detect truncation)",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "raw_logs",
        "last_processed_line",
        existing_type=sa.INTEGER(),
        comment="Line number for debugging/human readability",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "raw_logs",
        "last_processed_offset",
        existing_type=sa.INTEGER(),
        comment="Byte offset in file where we last stopped parsing",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_column("projects", "workspace_id")
    op.create_unique_constraint(
        op.f("messages_epoch_id_sequence_key"),
        "messages",
        ["epoch_id", "sequence"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_messages_timestamp"), "messages", ["timestamp"], unique=False
    )
    op.create_index(op.f("idx_messages_epoch"), "messages", ["epoch_id"], unique=False)
    op.create_index(
        op.f("idx_messages_entities"),
        "messages",
        ["entities"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_messages_conversation_role"),
        "messages",
        ["conversation_id", "role"],
        unique=False,
    )
    op.create_index(
        op.f("idx_messages_conversation"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("idx_messages_content_fts"),
        "messages",
        [sa.literal_column("to_tsvector('english'::regconfig, content)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_constraint(None, "ingestion_jobs", type_="foreignkey")
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_started_at"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_source_type"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_collector_id"), table_name="ingestion_jobs")
    op.create_index(
        op.f("idx_ingestion_jobs_status_time"),
        "ingestion_jobs",
        ["status", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_ingestion_jobs_started_at"),
        "ingestion_jobs",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_ingestion_jobs_source_type"),
        "ingestion_jobs",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_ingestion_jobs_source_time"),
        "ingestion_jobs",
        ["source_type", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_ingestion_jobs_source_config"),
        "ingestion_jobs",
        ["source_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_ingestion_jobs_failed"),
        "ingestion_jobs",
        [sa.literal_column("started_at DESC")],
        unique=False,
        postgresql_where="((status)::text = 'failed'::text)",
    )
    op.create_index(
        op.f("idx_ingestion_jobs_conversation"),
        "ingestion_jobs",
        ["conversation_id"],
        unique=False,
    )
    op.drop_column("ingestion_jobs", "collector_id")
    op.create_index(
        op.f("idx_files_path"), "files_touched", ["file_path"], unique=False
    )
    op.create_index(
        op.f("idx_files_epoch"), "files_touched", ["epoch_id"], unique=False
    )
    op.create_index(
        op.f("idx_files_conversation"),
        "files_touched",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("idx_epochs_time"), "epochs", ["start_time"], unique=False)
    op.create_index(op.f("idx_epochs_sentiment"), "epochs", ["sentiment"], unique=False)
    op.create_index(op.f("idx_epochs_intent"), "epochs", ["intent"], unique=False)
    op.create_index(
        op.f("idx_epochs_conversation"), "epochs", ["conversation_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("epochs_conversation_id_sequence_key"),
        "epochs",
        ["conversation_id", "sequence"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "developers", type_="foreignkey")
    op.drop_index(op.f("ix_developers_workspace_id"), table_name="developers")
    op.drop_column("developers", "workspace_id")
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_index(op.f("ix_conversations_workspace_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_updated_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_success"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_collector_id"), table_name="conversations")
    op.create_index(
        op.f("idx_conversations_updated_at"),
        "conversations",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_time"), "conversations", ["start_time"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_tags"),
        "conversations",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_conversations_success_nonnull"),
        "conversations",
        ["success"],
        unique=False,
        postgresql_where="(success IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_conversations_success"), "conversations", ["success"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_status_time"),
        "conversations",
        ["status", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_status"), "conversations", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_project_time"),
        "conversations",
        ["project_id", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_project"), "conversations", ["project_id"], unique=False
    )
    op.create_index(
        op.f("idx_conversations_developer_time"),
        "conversations",
        ["developer_id", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_developer"),
        "conversations",
        ["developer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_agent_time"),
        "conversations",
        ["agent_type", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_agent"), "conversations", ["agent_type"], unique=False
    )
    op.drop_column("conversations", "collector_id")
    op.drop_column("conversations", "workspace_id")
    op.create_index(
        op.f("idx_tags_value"), "conversation_tags", ["tag_value"], unique=False
    )
    op.create_index(
        op.f("idx_tags_type"), "conversation_tags", ["tag_type"], unique=False
    )
    op.create_index(
        op.f("idx_tags_conversation"),
        "conversation_tags",
        ["conversation_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("conversation_tags_conversation_id_tag_type_tag_value_key"),
        "conversation_tags",
        ["conversation_id", "tag_type", "tag_value"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_collector_configs_workspace_id"), table_name="collector_configs"
    )
    op.drop_index(
        op.f("ix_collector_configs_last_heartbeat"), table_name="collector_configs"
    )
    op.drop_index(
        op.f("ix_collector_configs_is_active"), table_name="collector_configs"
    )
    op.drop_index(
        op.f("ix_collector_configs_api_key_hash"), table_name="collector_configs"
    )
    op.drop_table("collector_configs")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_organization_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_is_active"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_is_active"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
