"""Add thinking_content to messages

Revision ID: c7f54635d2eb
Revises: c7103d6e90ac
Create Date: 2025-11-16 20:02:08.230534

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f54635d2eb"
down_revision: Union[str, None] = "c7103d6e90ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("thinking_content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "thinking_content")
    # ### end Alembic commands ###
