"""Add daemon_pid to watch_configurations

Revision ID: df336668f2bd
Revises: c7f54635d2eb
Create Date: 2025-11-17 21:39:00.680305

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df336668f2bd"
down_revision: Union[str, None] = "c7f54635d2eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watch_configurations", sa.Column("daemon_pid", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_watch_configurations_daemon_pid"),
        "watch_configurations",
        ["daemon_pid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_watch_configurations_daemon_pid"), table_name="watch_configurations"
    )
    op.drop_column("watch_configurations", "daemon_pid")
    # ### end Alembic commands ###
