"""Remove legacy conversation_tags table

Revision ID: e5adc1b6ec84
Revises: 1fa8bb9b5bfe
Create Date: 2025-11-21 22:47:14.441282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5adc1b6ec84"
down_revision: Union[str, None] = "1fa8bb9b5bfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_tags",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "tag_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "tag_value", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("conversation_tags_conversation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversation_tags_pkey")),
    )
    # ### end Alembic commands ###
